name: Villas Split Croatia
favicon: null
layout_spectrum: 0.16756668128073215
typography_spectrum: 0.08456154237501323
title: Croatian Villas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.46367957280017436
  lightness: 0.9721450612414628
  saturation: 0.7657940203789622
  rhythmicContrast: 0.5124804747756571
purpose: []
